# name of the software
name: AtlassianPS.github.io
# current version of the software
version: 0.1.0
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT
# extension of the favicon, blank to disable
favicon:

# default layouts
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "modules"
    values:
      layout: "module"

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/AtlassianPS/AtlassianPS.github.io
  - title: AtlassianPS
    url: http://AtlassianPS.org

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/AtlassianPS/AtlassianPS.github.io
  - title: Issues
    url: https://github.com/AtlassianPS/AtlassianPS.github.io/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user:
  repo:

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:


exclude: ['README.md', 'LICENSE', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
