# Website settings
title: AtlassianPS
description: A PowerShell community for Atlassian products
# description: A community for PowerShell lovers that use Atlassian products
keywords: Atlassian,AtlassianPS,jira,confluence,bitbucket,hipchat,jiraps,confluenceps,bitbucketps,hipchatps,github,gh-pages
baseurl: ""
url: "https://atlassianps.org"

# analytics
## google analytics
ga: UA-101621732-1

# Build settings
encoding: utf-8

# other settings
excerpt_separator: <!--more-->

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true
